package ort.edu.p1.tp3.ej12;

public class Test {
	public static void main(String[] args) {
		Centro centro1 = new Centro();
		Dia dia1 = new Dia("12/10/2020", true);
		Dia dia2 = new Dia("13/10/2020", true);
		Persona pers1 = new Persona("42654789", "Juan", "Perez", 35, MotivoTest.VIAJE);
		Persona pers5 = new Persona("36456987", "Carla", "Perez", 54, MotivoTest.VIAJE);

		Persona pers2 = new PersonaObraSocial("36456123" , "Miguel" , "Cervantes" , 48, MotivoTest.CONTACTO_ESTRECHO, "OSDE", 132546);
		Persona pers3 = new PersonaObraSocial("56754123" , "Carlos" , "Estevez" , 68, MotivoTest.REPETICION_POR_ERROR, "OSDE", 1787946);
		Persona pers4 = new PersonaObraSocial("1851425" , "Maria" , "Juarez" , 46, MotivoTest.REPETICION_POR_ERROR, "OSDE", 1787946);
		Persona pers6 = new PersonaObraSocial("1851425" , "Maria" , "Juarez" , 46, MotivoTest.REPETICION_POR_ERROR, "OSDE", 1787946);
		Persona pers7 = new PersonaObraSocial("1851425" , "Maria" , "Juarez" , 46, MotivoTest.REPETICION_POR_ERROR, "OSDE", 1787946);
		Persona pers8 = new PersonaObraSocial("1851425" , "Maria" , "Juarez" , 46, MotivoTest.REPETICION_POR_ERROR, "OSDE", 1787946);
		Persona pers9 = new PersonaObraSocial("1851425" , "Maria" , "Juarez" , 46, MotivoTest.REPETICION_POR_ERROR, "OSDE", 1787946);

		Persona pers10 = new PersonaObraSocial("1851425" , "Maria" , "Juarez" , 46, MotivoTest.REPETICION_POR_ERROR, "OSDE", 1787946);

		
		centro1.agregarDia(dia1);
		centro1.agregarDia(dia2);
		dia1.agregarPersonas(pers2)
		.agregarPersonas(pers1)
		.agregarPersonas(pers3)
		.agregarPersonas(pers4)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers6)
		.agregarPersonas(pers7)
		.agregarPersonas(pers8)
		.agregarPersonas(pers10)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers1)
		.agregarPersonas(pers3)
		.agregarPersonas(pers4)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers6)
		.agregarPersonas(pers7)
		.agregarPersonas(pers8)
		.agregarPersonas(pers10)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5).agregarPersonas(pers1)
		.agregarPersonas(pers3)
		.agregarPersonas(pers4)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers6)
		.agregarPersonas(pers7)
		.agregarPersonas(pers8)
		.agregarPersonas(pers10)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5).agregarPersonas(pers1)
		.agregarPersonas(pers3)
		.agregarPersonas(pers4)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers6)
		.agregarPersonas(pers7)
		.agregarPersonas(pers8)
		.agregarPersonas(pers10)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5).agregarPersonas(pers1)
		.agregarPersonas(pers3)
		.agregarPersonas(pers4)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers6)
		.agregarPersonas(pers7)
		.agregarPersonas(pers8)
		.agregarPersonas(pers10)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5).agregarPersonas(pers1)
		.agregarPersonas(pers3)
		.agregarPersonas(pers4)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers6)
		.agregarPersonas(pers7)
		.agregarPersonas(pers8)
		.agregarPersonas(pers10)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5).agregarPersonas(pers1)
		.agregarPersonas(pers3)
		.agregarPersonas(pers4)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers6)
		.agregarPersonas(pers7)
		.agregarPersonas(pers8)
		.agregarPersonas(pers10)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5).agregarPersonas(pers1)
		.agregarPersonas(pers3)
		.agregarPersonas(pers4)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers6)
		.agregarPersonas(pers7)
		.agregarPersonas(pers8)
		.agregarPersonas(pers10)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5).agregarPersonas(pers1)
		.agregarPersonas(pers3)
		.agregarPersonas(pers4)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers6)
		.agregarPersonas(pers7)
		.agregarPersonas(pers8)
		.agregarPersonas(pers10)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5).agregarPersonas(pers1)
		.agregarPersonas(pers3)
		.agregarPersonas(pers4)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers6)
		.agregarPersonas(pers7)
		.agregarPersonas(pers8)
		.agregarPersonas(pers10)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5).agregarPersonas(pers1)
		.agregarPersonas(pers3)
		.agregarPersonas(pers4)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers6)
		.agregarPersonas(pers7)
		.agregarPersonas(pers8)
		.agregarPersonas(pers10)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)
		.agregarPersonas(pers5)

		.agregarPersonas(pers5);
		dia2.agregarPersonas(pers1);
		System.out.println("porcentaje " + centro1.revisar());
		System.out.println("Promedio edad personas sin OS: " + dia1.promedioEdadPersonasSinOS() + "%");
		centro1.mostrarDiaConMasPrioritarios();
		
		
	}
}
